### ISSUE TITLE
Fix getProjects lib

### ISSUE THREAD

**Issue by jcserracampos** [guildatech/awesome-projects#5]
Eu nunca sei se preciso escrever os issues em inglês ou português... Eu acho que tem que ser em português para incluir mais pessoas... enfim...

Por algum motivo (eu acho que estou me perdendo nos async/await da vida) o método getProjects tá retornando nada.

**Comment by iagocavalcante** [comment]
Substituir 
`
const projects = projectsMarkdown
        .map(md => {
            metaMarked(md, { renderer: renderer })
        })
`

por 

`
const projects = projectsMarkdown
        .map(md => metaMarked(md, { renderer: renderer }))
`

**Comment by iagocavalcante** [comment]
Se for usar com chaves é preciso ser dessa forma 
`const projects = projectsMarkdown .map(md => { return metaMarked(md, { renderer: renderer }) })`
